### ISSUE TITLE
Difference between this plugin and Disable GitHub Multibranch Status

### ISSUE THREAD

**Issue by l3ender** [jenkinsci/skip-notifications-trait-plugin#112]
### Describe your use-case which is not covered by existing documentation.

The readme mentions this plugin is similar to the [Disable GitHub Multibranch Status plugin](https://plugins.jenkins.io/disable-github-multibranch-status/). I am confused between the two plugins and if they accomplish the same thing. Could elaboration be given on why both plugins exist, and any differences between the two?

Thanks!

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/disable-github-multibranch-status-plugin

**Comment by jonesbusy** [comment]
This plugin support Bitbucket and Github sources branches and can be extanded for more SCM.

I took maintenance one year ago so I don't know the reasons. Sometimes in the Jenkins plugin eco-system same or similar functionalities exists across plugins,

The plugin you mention looks abandoned without maintenance
